#pretending we're C because otherwise ruby will initialize, even with "language: dm".
language: c
sudo: false

env:
    global:
    - BYOND_MAJOR="510"
    - BYOND_MINOR="1333"
    matrix:
    - DM_MAPFILE="metastation"
    - DM_MAPFILE="ministation"

cache:
  directories:
    - $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}
  
addons:
  apt:
    packages:
      - libc6-i386
      - libgcc1:i386
      - libstdc++6:i386
      - python
      - python-pip
  
install:
  - pip install --user PyYaml -q
  - pip install --user beautifulsoup4 -q

before_script:
  - chmod +x ./install-byond.sh
  - ./install-byond.sh

script:
  - shopt -s globstar
  - (! grep 'step_[xy]' _maps/**/*.dmm)
  - source $HOME/BYOND-${BYOND_MAJOR}.${BYOND_MINOR}/byond/bin/byondsetup
  - bash dm.sh -M${DM_MAPFILE} tgstation.dme
